/**
 * 
 */

const WIDTH 	= 1000;
const HEIGHT	= 1000;

const MAX_VERTICES = 10;
const MAX_POLYGONS = 10;
const MAX_POPULATION = 4;

const DEFAULT_MUTATION_PROBABILITY = 0.0001; 

const DEFAULT_FITNESS = 1;

const TIMEOUT = 10;